### ISSUE TITLE
It's possible create name ID with space, but other command don't take "id with space"

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/EasyRanking#1]
**Spigot version / Paper version**
Paper ex. 333, minecraft 1.15.2

**Easyranking version**
0.0.1

**Describe the bug**
When i create a ranking i can type character with space for ID ranking.
Other command don't recognize ranking with name with space.

**To Reproduce**
Type /er create
type name ID with phrase with space.

**Expected behavior**
The other command of plugin recognize ranking with phrase with space or it's not possible write phrase with space for ID ranking.

**Comment by simonerighi96** [comment]
Fixed with ec693e4dcda745d1fe25553139fb6274ae10d1c5
