### ISSUE TITLE
Er count destroy event in plot where you don't have permission

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/EasyRanking#2]
**Spigot version / Paper version**
Spigot ex. 1.15.2
Paper ex. 333

**Easyranking version**
Ex. 0.0.1

**Describe the bug**
When i destroy one ore block in plot or chunk where towny blocks my perms, ER count my destroy for ranking.

**To Reproduce**
1. Go in plot or towny where you don't have permission for destroy.
2. destroy one ore.
3. ER count the event, Towny don't destroy block (because you don't have permission.
4) repeat

**Expected behavior**
ER don't count the false destroy.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/5273405/84701444-4e5cb180-af55-11ea-8da3-d4133c156d62.png)
![immagine](https://user-images.githubusercontent.com/5273405/84701458-53216580-af55-11ea-8dae-06b9f85fbb7d.png)

**Comment by simonerighi96** [comment]
Fixed with 2c116eed75e3f774fd66944809d5ef22427936cf
